CREATE TYPE "Role_new" AS ENUM ('ADMINISTRADOR', 'COLABORADOR', 'CLIENTE');
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role_new" USING (
  CASE "role"::text
    WHEN 'ADMIN' THEN 'ADMINISTRADOR'::"Role_new"
    WHEN 'COLLABORATOR' THEN 'COLABORADOR'::"Role_new"
    WHEN 'CLIENT' THEN 'CLIENTE'::"Role_new"
  END
);
DROP TYPE "Role";
ALTER TYPE "Role_new" RENAME TO "Role";
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'CLIENTE';
